{% set name = "cuda-cuxxfilt" %}
{% set version = "13.0.39" %}
{% set cuda_version = "13.0" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win]
{% set target_name = "x86_64-linux" %}  # [linux64]
{% set target_name = "ppc64le-linux" %}  # [ppc64le]
{% set target_name = "sbsa-linux" %}  # [aarch64]
{% set target_name = "x64" %}  # [win]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_cuxxfilt/{{ platform }}/cuda_cuxxfilt-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: 4308ef419d8da4553f4816b2fc485c099351fcf186f835d6e8d4795f89aa41ed  # [linux64]
  sha256: b1fb6e94771224125e6e3e5a2dbd2533a9326e18d771519b6e02accdf9825766  # [aarch64]
  sha256: d54303fbb4404ccb6d0610fff95f69f8c7d7ab27a38ec16f223f6318c1508653  # [win]

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}

test:
  requires:
    - patchelf  # [linux]
  files:
    - test-rpath.sh
  commands:
    - test -f $PREFIX/bin/cu++filt                                   # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/include/nv_decode.h  # [linux]
    - test -f $PREFIX/targets/{{ target_name }}/lib/libcufilt.a      # [linux]
    - bash test-rpath.sh                                             # [linux]
    - if not exist %LIBRARY_BIN%\cu++filt.exe exit 1                 # [win]
    - if not exist %LIBRARY_INC%\\nv_decode.h exit 1                 # [win]
    - if not exist %LIBRARY_LIB%\{{ target_name }}\cufilt.lib exit 1  # [win]

about:
  home: https://developer.nvidia.com/cuda-toolkit
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: cu++filt decodes low-level identifiers that have been mangled by CUDA C++
  description: |
    cu++filt decodes (demangles) low-level identifiers that have been mangled by
    CUDA C++ into user readable names. For every input alphanumeric word, the
    output of cu++filt is either the demangled name if the name decodes to a CUDA
    C++ name, or the original name itself.
  doc_url: https://docs.nvidia.com/cuda/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
